# Test config file for Blip
module:
  module_name:  'corenet_v2'
  module_type:  ['ml']
  module_mode:  ['inference']
  local_run:    ''
  gpu:          True
  gpu_device:   0
  verbose:      False

dataset:
  dataset_folder: ""
  dataset_files:  []
  dataset_type:   'cmssm'
  normalized:     true
  training:       false
  norm_params:    "norm_params.npz"
  # ---- variables ----
  # Here we specify the location of the GUT variables in the files
  # and the weak values associated to the trial points.
  gut_test: [0,5]
  gut_true: [7,12]
  weak_test: [5,7]
  labels: []
  # ---- normalization ----
  # Normalization parameters for positions and features.  Typically we want to normalize
  # input features depending on the type of task, or to unbias certain simulation parameters,
  # e.g. by normalizaing ADC over an event sample we remove the overall scale of the detector
  # response.
  position_normalization:   []
  features_normalization:   []

loader:
  loader_type:      ""
  batch_size:       5000
  test_split:       0.1
  test_seed:        0
  validation_split: 0.3
  validation_seed:  0
  num_workers:      8

inference:
  dataset_type: 'all'
  progress_bar: true 
  rewrite_bar:  false # wether to leave bars after each epoch
  save_predictions: true  # wether to save network outputs
  layers: []
  prediction_outputs: [
    'gut_test', 'weak_test',
    'gut_test_latent', 'weak_test_latent',
    'gut_test_output', 'weak_test_output'
  ]
  skip_metrics: False

model:
  # uncomment the line below and specify the model to load from a checkpoint.
  load_model:   "CORENet_trained_params.ckpt"
  model_config: "CORENet_init.config"
  model_type: CORENet