# Test config for MSSM
mssm:
  verbose:   true
  mssm_folder:  '/mssm_data/corenet_v2_100_epoch_decoder_dropout_03_100_100_100_100_100_2025.2.12.7.46.31/'
  mssm_files:   ['corenet_v2_2025.2.15.16.45.1.npz']
  normalization_file: '/local_corenet/data/cmssm_norm.npz'
  skip_files: []
  param_space: 'cmssm'
  softsusy_dir: '/workspace/softsusy/'
  micromegas_dir: '/workspace/micromegas/MSSM/'
