# Test config for MSSM
mssm:
  verbose:   true
  mssm_folder:  '/mssm_data/corenet_v3_100_epoch_decoder_dropout_03_25_50_25_2025.1.20.10.8.5/'
  mssm_files:   ['corenet_v1_2025.1.28.10.41.51.npz']
  normalization_file: '/local_data/generated/cmssm_100K/100K_samples_generated_points_norm.npz'
  skip_files: []
  param_space: 'cmssm'
  softsusy_dir: '/workspace/softsusy/'
  micromegas_dir: '/workspace/micromegas/MSSM/'
