# Test config for MSSM
mssm:
  verbose:   true
  mssm_folder:  '/mssm_data/'
  mssm_files:   ['corenet_v1_2025.1.27.10.7.47.npz']
  normalization_file: '/local_data/generated/cmssm_random_new_01_tophat_generated_points_norm.npz'
  skip_files: []
  param_space: 'cmssm'
  softsusy_dir: '/workspace/softsusy/'
  micromegas_dir: '/workspace/micromegas/MSSM/'
